stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: freddyiw/my-pet-clinic-3
  DOCKER_TAG: latest

build_job_1:
  stage: build
  image: gradle:7.6-jdk17
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    TESTCONTAINERS_RYUK_DISABLED: true
  services:
    - docker:dind
  script:
    - ./gradlew build -Dtestcontainers.use.docker.host=true
  artifacts:
    paths:
      - build/libs/spring-petclinic-3.1.0.jar
    expire_in: 1 hour

build_job_2:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
    - docker push $DOCKER_IMAGE:$DOCKER_TAG
  needs:
    - job: build_job_1
      artifacts: true

deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  before_script:
    - echo "$KUBE_CONFIG" | base64 -d > kubeconfig
    - export KUBECONFIG=$CI_PROJECT_DIR/kubeconfig
  script:
    - kubectl apply -f petclinic-deployment.yaml
    - kubectl rollout restart deployment petclinic
  only:
    - main
